/**
 * Server-side PDF generation (pdfkit) → upload to the Supabase `documents`
 * bucket → return a signed URL that WhatsApp can fetch. Real, no mock.
 */
import PDFDocument from "pdfkit";
import { getServiceClient } from "../supabase";

// Kaunta brand palette (mirrors the design system).
export const BRAND = {
  ink: "#0F1923",
  slate: "#1C2B3A",
  copper: "#C4622D",
  sage: "#3D6B5E",
  stone: "#F7F4F0",
  mist: "#EAE6E1",
  red: "#B83232",
  muted: "#6B7280",
};

export const fmtKes = (n: number) =>
  `KES ${Number(n ?? 0).toLocaleString("en-KE", { maximumFractionDigits: 0 })}`;

/** Render a pdfkit document (via a draw callback) to a Buffer. */
export function renderToBuffer(draw: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    try {
      draw(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Upload a PDF buffer to `documents/<path>` and return a signed URL.
 * @param signedTtlSec how long the signed URL stays valid (default 7 days)
 */
export async function uploadPdf(
  path: string,
  buffer: Buffer,
  signedTtlSec = 7 * 24 * 3600
): Promise<{ path: string; signedUrl: string }> {
  const db = getServiceClient();
  const { error } = await db.storage.from("documents").upload(path, buffer, {
    contentType: "application/pdf",
    upsert: true,
  });
  if (error) throw new Error(`[pdf] upload failed: ${error.message}`);

  const { data, error: signErr } = await db.storage
    .from("documents")
    .createSignedUrl(path, signedTtlSec);
  if (signErr || !data) throw new Error(`[pdf] sign failed: ${signErr?.message}`);

  return { path, signedUrl: data.signedUrl };
}

// ── Shared drawing helpers ───────────────────────────────────────────────────
export function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  doc.fillColor(BRAND.copper).fontSize(22).font("Helvetica-Bold").text("Kaunta", { continued: false });
  doc.moveDown(0.2);
  doc.fillColor(BRAND.ink).fontSize(16).font("Helvetica-Bold").text(title);
  if (subtitle) {
    doc.fillColor(BRAND.muted).fontSize(10).font("Helvetica").text(subtitle);
  }
  doc.moveDown(0.5);
  doc
    .strokeColor(BRAND.mist)
    .lineWidth(1)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(1);
}

export function drawFooter(doc: PDFKit.PDFDocument) {
  const y = doc.page.height - doc.page.margins.bottom - 10;
  doc
    .fillColor(BRAND.muted)
    .fontSize(8)
    .font("Helvetica")
    .text(`Generated by Kaunta-HR · ${new Date().toLocaleString("en-KE")}`, doc.page.margins.left, y, {
      align: "center",
      width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
    });
}
